### ISSUE TITLE
code/7 is mistake

### ISSUE THREAD

**Issue by kosei16** [ats1104/ComputerVison_homework#1]
コード共有ありがとうございます。

コードに関しての質問なのですが

images[labels[i]].copyTo(target);

この部分ではイメージそのものをターゲットにしており、検出した画像ではないように見受けられます。
このまま検出すれば確かに精度は高いのですが、どうでしょうか、、、

確認よろしくお願いします。

**Comment by ats1104** [comment]
ご指摘いただいた箇所は，おっしゃる通り「イメージそのものをターゲットにしており検出した画像」ではありません．
が，イメージそのものをターゲットにした場合，ちゃんと復元できて検出精度も高くなるのかを確認するためにやっています．

課題である，検出された画像に対する復元と検出に関しましては，268行目〜の部分にコードを書いております．
//検出画像の復元
からです．

ご確認よろしくお願いします．

**Comment by kosei16** [comment]
> コード共有ありがとうございます。
> 
> コードに関しての質問なのですが
> 
> images[labels[i]].copyTo(target);
> 
> この部分ではイメージそのものをターゲットにしており、検出した画像ではないように見受けられます。 このまま検出すれば確かに精度は高いのですが、どうでしょうか、、、
> 
> 確認よろしくお願いします。酢飯
